apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stayspotter-mongodb
spec:
  serviceName: "stayspotter-mongodb"
  replicas: 3
  selector:
    matchLabels:
      app: stayspotter-mongodb
  template:
    metadata:
      labels:
        app: stayspotter-mongodb
    spec:
      containers:
      - name: stayspotter-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  # volumeClaimTemplates:
  # - metadata:
  #     name: mongodb-data
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: "gp2"
  #     resources:
  #       requests:
  #         storage: 1Gi
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: stayspotter-ebs-pvc
