apiVersion: apps/v1
kind: Deployment
metadata:
  name: stayspotter-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stayspotter-api
  template:
    metadata:
      labels:
        app: stayspotter-api
    spec:
      containers:
      - name: stayspotter-api
        image: tyagiharsh7/stay-spotter-api:latest
        ports:
        - containerPort: 8800
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: stayspotter-config
              key: PORT
        - name: MONGO
          valueFrom:
            secretKeyRef:
              name: stayspotter-secret
              key: MONGO
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: stayspotter-secret
              key: JWTSECRET
