apiVersion: apps/v1
kind: Deployment
metadata:
  name: stayspotter-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stayspotter-client
  template:
    metadata:
      labels:
        app: stayspotter-client
    spec:
      containers:
      - name: stayspotter-client
        image: tyagiharsh7/stay-spotter-client:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_BASE_API_URI
          valueFrom:
            configMapKeyRef:
              name: stayspotter-config
              key: VITE_BASE_API_URI
        - name: VITE_BASE_DEFAULT_CITY
          valueFrom:
            configMapKeyRef:
              name: stayspotter-config
              key: VITE_BASE_DEFAULT_CITY